### ISSUE TITLE
Negative information

### ISSUE THREAD

**Issue by saketkc** [mjcasy/infohet#2]
Hi @mjcasy, Had lot of fun reading the preprint!

I was able to run and replicate the example from the README. But on trying on some other public datasets, I get a negative information (object attached - PBMC3k):

```r
pbmc3k <- readRDS("pbmc3k_seurat.rds")
CountsMatrix <- pbmc3k@assays$RNA@counts
CountsMatrix <- CountsMatrix[rowSums(CountsMatrix) > 100,]

Information <- getHet(CountsMatrix)

HighlyInformative <- Information > 1

N <- CountsMatrix@Dim[2]
Mean <- log10(rowMeans(CountsMatrix))

HetDataFrame <- data.frame(Mean, Information)

ColourSelected <- brewer.pal(9, "Blues")[8]
ColourNotSelected <- brewer.pal(9, "Blues")[4]

plot(HetDataFrame$Mean, 
     HetDataFrame$Information,
     col = ifelse(HighlyInformative, ColourSelected, ColourNotSelected),
     ylim = c(0, log2(N)),
     pch = 20)
SeuObj <- Seurat::CreateSeuratObject(CountsMatrix)
SeuObj <- Seurat::SCTransform(SeuObj, method="glmGamPoi")
Data <- SeuObj@assays$SCT@scale.data

SeuObj <- RunPCA(SeuObj, verbose = FALSE)
SeuObj <- FindNeighbors(SeuObj, dims = 1:30, verbose = FALSE)
DimPlot(SeuObj)

Resolutions <- c(seq(0.0001, 0.001, 0.0001), seq(0.002, 0.01, 0.001), seq(0.02, 0.2, 0.01), seq(0.3, 1, 0.1))

NumClusters <- c()
NetInformation <- c()

for(i in 1:length(Resolutions)){
  Idents(SeuObj) <- NA
  
  SeuObj <- FindClusters(SeuObj, verbose = FALSE, resolution = Resolutions[i])
  
  Identity <- Idents(SeuObj)
  
  NetInformation[i] <- netInformation(CountsMatrix, Identity, Information)
  
  NumClusters[i] <- length(levels(Identity))
}

Elbow <- cbind(Resolutions, NumClusters, NetInformation)
Elbow <- as.data.frame(Elbow)
plot(Elbow$NumClusters, 
     Elbow$NetInformation)
plot(Elbow$Resolutions, 
     Elbow$NetInformation)
```

Looking into the code now, but am I missing anything obvious?
![image](https://user-images.githubusercontent.com/682153/116835285-d066c080-ab8f-11eb-82b8-026cc9e84ad6.png)

[pbmc3k_seurat.rds.tar.gz](https://github.com/mjcasy/infohet/files/6412608/pbmc3k_seurat.rds.tar.gz)

**Comment by mjcasy** [comment]
Hi @saketkc, glad you enjoyed the preprint!

Just to note that when I attempted to download the pmbc_3k file, my laptop reported it as being empty; I assumed it was the one from the Seurat tutorial, so have used that (https://satijalab.org/seurat/archive/v3.1/pbmc3k_tutorial.html).

The negative information is a problem of regularisation: net information is the total information obtained from a clustering minus the scaled entropy of the clustering.

The entropy of the clustering, H(S), is based on the fraction of cells assigned to each cluster.

We scale it through the lambda quantity, so lambda * H(S).

The default for lambda (an argument in the netInformation function) is sum(Information) / log2(Number of Cells); whenever each cell is its own cluster, the netInformation will be zero.

This is, however, a harsh regularisation – it, informally, assumes that most of the heterogeneity will be explained as differences between clusters. When there is substantial intra-cluster heterogeneity relative to inter-cluster difference, the scaling can be overly harsh.

In this case, you need to multiply lambda with a modifier from the range [0,1]: too low a modifier and the net information will keep increasing for very large numbers of clusters; too high and you get negative net information immediately. If we multiply the scaling term by 0.4, the peak information is now 8 clusters.

Manual modification is not as nice as having a universal default, and I am working on it; but, the stronger the peak, the more robust it should be to the choice of multiple.

Thanks for pointing this out; I will try and add some detail to the net information function!

```
Lambda <- 0.4 * sum(Information) / log2(ncol(CountsMatrix))

for(i in 1:length(Resolutions)){
  Idents(SeuObj) <- NA
  
  SeuObj <- FindClusters(SeuObj, verbose = FALSE, resolution = Resolutions[i])
  
  Identity <- Idents(SeuObj)
  
  NetInformation[i] <- netInformation(CountsMatrix, Identity, Information, lambda = Lambda)
  
  NumClusters[i] <- length(levels(Identity))
}

plot(NumClusters, NetInformation)
abline(v = 8, col = "red")
```

![image](https://user-images.githubusercontent.com/44202821/116864560-f3c95400-abff-11eb-90b2-285e38ea9516.png)

**Comment by mjcasy** [comment]
Hi @saketkc, I’ve modified the netInformation function, so instead of setting lambda in full, you can now just provide the multiple (the 0.4 in my above comment). The default is identical.
